# See http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring.thymeleaf.cache=false
spring.main.show-banner=false
logging.level.jdbc=OFF
logging.level.jdbc.sqltiming=DEBUG
logging.level.jdbc.resultsettable=DEBUG

spring.datasource.url=jdbc:mysql://localhost:3306/bankingApp
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=FruitsBasket
spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect


<!--currency.api.url="http://data.fixer.io/api/" -->
currency.api.key=e6ec88c9b5c8ceba8b39032cd56c94bb

spring.jpa.open-in-view=false

# Enable caching
spring.cache.type=simple

# Enable logging for cache operations
logging.level.org.springframework.cache=DEBUG
